// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot'

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  AdminMdnPreloadData,
  AdminMdnPreloadErrors,
  AdminMdnPreloadResponses,
  CommentsDeleteData,
  CommentsDeleteErrors,
  CommentsDeleteResponses,
  CommentsRepliesCreateData,
  CommentsRepliesCreateErrors,
  CommentsRepliesCreateResponses,
  CommentsRepliesListData,
  CommentsRepliesListResponses,
  FeedListData,
  FeedListResponses,
  PostsCommentsCreateData,
  PostsCommentsCreateErrors,
  PostsCommentsCreateResponses,
  PostsCommentsListData,
  PostsCommentsListResponses,
  PostsVotesToggleData,
  PostsVotesToggleErrors,
  PostsVotesToggleResponses,
  ResolveMdnData,
  ResolveMdnErrors,
  ResolveMdnResponses,
  SessionMeGetData,
  SessionMeGetErrors,
  SessionMeGetResponses,
  SystemDbPingData,
  SystemDbPingErrors,
  SystemDbPingResponses,
  SystemHealthData,
  SystemHealthResponses,
  TopicsGetLinksData,
  TopicsGetLinksResponses,
  TopicsGetPostsData,
  TopicsGetPostsErrors,
  TopicsGetPostsResponses,
} from './types.gen'
import {
  vAdminMdnPreloadData,
  vAdminMdnPreloadResponse,
  vCommentsDeleteData,
  vCommentsDeleteResponse,
  vCommentsRepliesCreateData,
  vCommentsRepliesCreateResponse,
  vCommentsRepliesListData,
  vCommentsRepliesListResponse,
  vFeedListData,
  vFeedListResponse,
  vPostsCommentsCreateData,
  vPostsCommentsCreateResponse,
  vPostsCommentsListData,
  vPostsCommentsListResponse,
  vPostsVotesToggleData,
  vPostsVotesToggleResponse,
  vResolveMdnData,
  vResolveMdnResponse2,
  vSessionMeGetData,
  vSessionMeGetResponse,
  vSystemDbPingData,
  vSystemHealthData,
  vTopicsGetLinksData,
  vTopicsGetLinksResponse,
  vTopicsGetPostsData,
  vTopicsGetPostsResponse,
} from './valibot.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Enqueues batch MDN fetch_raw jobs (dev/admin)
 */
export const adminMdnPreload = <ThrowOnError extends boolean = false>(
  options: Options<AdminMdnPreloadData, ThrowOnError>,
) =>
  (options.client ?? client).post<AdminMdnPreloadResponses, AdminMdnPreloadErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vAdminMdnPreloadData, data),
    responseValidator: async (data) => await v.parseAsync(vAdminMdnPreloadResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/mdn/preload',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Returns posts for a topic
 */
export const topicsGetPosts = <ThrowOnError extends boolean = false>(
  options: Options<TopicsGetPostsData, ThrowOnError>,
) =>
  (options.client ?? client).get<TopicsGetPostsResponses, TopicsGetPostsErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vTopicsGetPostsData, data),
    responseValidator: async (data) => await v.parseAsync(vTopicsGetPostsResponse, data),
    url: '/api/topics/{slug}',
    ...options,
  })

/**
 * Returns linked topics for a topic
 */
export const topicsGetLinks = <ThrowOnError extends boolean = false>(
  options: Options<TopicsGetLinksData, ThrowOnError>,
) =>
  (options.client ?? client).get<TopicsGetLinksResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vTopicsGetLinksData, data),
    responseValidator: async (data) => await v.parseAsync(vTopicsGetLinksResponse, data),
    url: '/api/topics/{slug}/links',
    ...options,
  })

/**
 * Health check
 */
export const systemHealth = <ThrowOnError extends boolean = false>(
  options?: Options<SystemHealthData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SystemHealthResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vSystemHealthData, data),
    url: '/api/health',
    ...options,
  })

/**
 * Checks DB connectivity
 */
export const systemDbPing = <ThrowOnError extends boolean = false>(
  options?: Options<SystemDbPingData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SystemDbPingResponses, SystemDbPingErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vSystemDbPingData, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/db/ping',
    ...options,
  })

/**
 * Returns the current user id from Supabase JWT
 */
export const sessionMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<SessionMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SessionMeGetResponses, SessionMeGetErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vSessionMeGetData, data),
    responseValidator: async (data) => await v.parseAsync(vSessionMeGetResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/me',
    ...options,
  })

/**
 * Resolves an MDN external path to a DocTok topic
 */
export const resolveMdn = <ThrowOnError extends boolean = false>(
  options: Options<ResolveMdnData, ThrowOnError>,
) =>
  (options.client ?? client).get<ResolveMdnResponses, ResolveMdnErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vResolveMdnData, data),
    responseValidator: async (data) => await v.parseAsync(vResolveMdnResponse2, data),
    url: '/api/resolve/mdn/{externalRef}',
    ...options,
  })

/**
 * Toggles a like or dislike on a post
 */
export const postsVotesToggle = <ThrowOnError extends boolean = false>(
  options: Options<PostsVotesToggleData, ThrowOnError>,
) =>
  (options.client ?? client).put<PostsVotesToggleResponses, PostsVotesToggleErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vPostsVotesToggleData, data),
    responseValidator: async (data) => await v.parseAsync(vPostsVotesToggleResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{postId}/vote',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Returns paginated feed items
 */
export const feedList = <ThrowOnError extends boolean = false>(
  options?: Options<FeedListData, ThrowOnError>,
) =>
  (options?.client ?? client).get<FeedListResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vFeedListData, data),
    responseValidator: async (data) => await v.parseAsync(vFeedListResponse, data),
    url: '/api/feed',
    ...options,
  })

/**
 * Returns replies for a root comment
 */
export const commentsRepliesList = <ThrowOnError extends boolean = false>(
  options: Options<CommentsRepliesListData, ThrowOnError>,
) =>
  (options.client ?? client).get<CommentsRepliesListResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vCommentsRepliesListData, data),
    responseValidator: async (data) => await v.parseAsync(vCommentsRepliesListResponse, data),
    url: '/api/comments/{commentId}/replies',
    ...options,
  })

/**
 * Adds a reply to a root comment
 */
export const commentsRepliesCreate = <ThrowOnError extends boolean = false>(
  options: Options<CommentsRepliesCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CommentsRepliesCreateResponses,
    CommentsRepliesCreateErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await v.parseAsync(vCommentsRepliesCreateData, data),
    responseValidator: async (data) => await v.parseAsync(vCommentsRepliesCreateResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/comments/{commentId}/replies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Returns root comments for a post
 */
export const postsCommentsList = <ThrowOnError extends boolean = false>(
  options: Options<PostsCommentsListData, ThrowOnError>,
) =>
  (options.client ?? client).get<PostsCommentsListResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vPostsCommentsListData, data),
    responseValidator: async (data) => await v.parseAsync(vPostsCommentsListResponse, data),
    url: '/api/posts/{postId}/comments',
    ...options,
  })

/**
 * Adds a comment to a post
 */
export const postsCommentsCreate = <ThrowOnError extends boolean = false>(
  options: Options<PostsCommentsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostsCommentsCreateResponses,
    PostsCommentsCreateErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await v.parseAsync(vPostsCommentsCreateData, data),
    responseValidator: async (data) => await v.parseAsync(vPostsCommentsCreateResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{postId}/comments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Soft-deletes a comment owned by the current user
 */
export const commentsDelete = <ThrowOnError extends boolean = false>(
  options: Options<CommentsDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CommentsDeleteResponses, CommentsDeleteErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vCommentsDeleteData, data),
    responseValidator: async (data) => await v.parseAsync(vCommentsDeleteResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/comments/{commentId}',
    ...options,
  })
