// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5005/' | (string & {})
}

export type Comment = {
  id: number | string
  postId: number | string
  userId: string
  parentCommentId: null | number | string
  body: string
  createdAt: string
  isDeleted: boolean
}

export type CreateCommentRequest = {
  body: string
}

export type FeedResponse = {
  items: Array<PostItem>
  nextCursor: null | string
}

export type PostItem = {
  id: number | string
  kind: string
  title: string
  body: string
  position: number | string
  likeCount: number | string
  dislikeCount: number | string
  commentCount: number | string
  topicSlug: string
  topicTitle: string
  myVote: string
  popularity: null | number | string
}

export type PreloadMdnRequest = {
  lang: string
  count: number | string
  seed: null | number | string
  prefix: null | string
}

export type PreloadMdnResponse = {
  sample: Array<string>
}

export type ResolveMdnResponse = {
  status: string
  topicSlug: null | string
  lang: null | string
  jobId: null | number | string
}

export type SessionMeResponse = {
  userId: string
  email: null | string
}

export type TogglePostVoteRequest = {
  value: VoteValue
}

export type TopicLink = {
  slug: string
  title: string
}

export type TopicPostsResponse = {
  items: Array<PostItem>
}

export type VoteResult = {
  myVote: string
  likeCount: number | string
  dislikeCount: number | string
}

export type VoteValue = number

export type AdminMdnPreloadData = {
  body: PreloadMdnRequest
  path?: never
  query?: never
  url: '/api/admin/mdn/preload'
}

export type AdminMdnPreloadErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
}

export type AdminMdnPreloadResponses = {
  /**
   * OK
   */
  200: PreloadMdnResponse
}

export type AdminMdnPreloadResponse = AdminMdnPreloadResponses[keyof AdminMdnPreloadResponses]

export type TopicsGetPostsData = {
  body?: never
  path: {
    slug: string
  }
  query?: {
    lang?: string
  }
  url: '/api/topics/{slug}'
}

export type TopicsGetPostsErrors = {
  /**
   * Not Found
   */
  404: unknown
}

export type TopicsGetPostsResponses = {
  /**
   * OK
   */
  200: TopicPostsResponse
}

export type TopicsGetPostsResponse = TopicsGetPostsResponses[keyof TopicsGetPostsResponses]

export type TopicsGetLinksData = {
  body?: never
  path: {
    slug: string
  }
  query?: {
    lang?: string
  }
  url: '/api/topics/{slug}/links'
}

export type TopicsGetLinksResponses = {
  /**
   * OK
   */
  200: Array<TopicLink>
}

export type TopicsGetLinksResponse = TopicsGetLinksResponses[keyof TopicsGetLinksResponses]

export type SystemHealthData = {
  body?: never
  path?: never
  query?: never
  url: '/api/health'
}

export type SystemHealthResponses = {
  /**
   * OK
   */
  200: unknown
}

export type SystemDbPingData = {
  body?: never
  path?: never
  query?: never
  url: '/api/db/ping'
}

export type SystemDbPingErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
}

export type SystemDbPingResponses = {
  /**
   * OK
   */
  200: unknown
}

export type SessionMeGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/me'
}

export type SessionMeGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
}

export type SessionMeGetResponses = {
  /**
   * OK
   */
  200: SessionMeResponse
}

export type SessionMeGetResponse = SessionMeGetResponses[keyof SessionMeGetResponses]

export type ResolveMdnData = {
  body?: never
  path: {
    externalRef: string
  }
  query?: {
    lang?: string
  }
  url: '/api/resolve/mdn/{externalRef}'
}

export type ResolveMdnErrors = {
  /**
   * Bad Request
   */
  400: unknown
}

export type ResolveMdnResponses = {
  /**
   * OK
   */
  200: ResolveMdnResponse
}

export type ResolveMdnResponse2 = ResolveMdnResponses[keyof ResolveMdnResponses]

export type PostsVotesToggleData = {
  body: TogglePostVoteRequest
  path: {
    postId: number
  }
  query?: never
  url: '/api/posts/{postId}/vote'
}

export type PostsVotesToggleErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Not Found
   */
  404: unknown
}

export type PostsVotesToggleResponses = {
  /**
   * OK
   */
  200: VoteResult
}

export type PostsVotesToggleResponse = PostsVotesToggleResponses[keyof PostsVotesToggleResponses]

export type FeedListData = {
  body?: never
  path?: never
  query?: {
    cursor?: string
    lang?: string
    limit?: number | string
  }
  url: '/api/feed'
}

export type FeedListResponses = {
  /**
   * OK
   */
  200: FeedResponse
}

export type FeedListResponse = FeedListResponses[keyof FeedListResponses]

export type CommentsRepliesListData = {
  body?: never
  path: {
    commentId: number
  }
  query?: {
    limit?: number | string
  }
  url: '/api/comments/{commentId}/replies'
}

export type CommentsRepliesListResponses = {
  /**
   * OK
   */
  200: Array<Comment>
}

export type CommentsRepliesListResponse =
  CommentsRepliesListResponses[keyof CommentsRepliesListResponses]

export type CommentsRepliesCreateData = {
  body: CreateCommentRequest
  path: {
    commentId: number
  }
  query?: never
  url: '/api/comments/{commentId}/replies'
}

export type CommentsRepliesCreateErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Not Found
   */
  404: unknown
}

export type CommentsRepliesCreateResponses = {
  /**
   * Created
   */
  201: Comment
}

export type CommentsRepliesCreateResponse =
  CommentsRepliesCreateResponses[keyof CommentsRepliesCreateResponses]

export type PostsCommentsListData = {
  body?: never
  path: {
    postId: number
  }
  query?: {
    limit?: number | string
  }
  url: '/api/posts/{postId}/comments'
}

export type PostsCommentsListResponses = {
  /**
   * OK
   */
  200: Array<Comment>
}

export type PostsCommentsListResponse = PostsCommentsListResponses[keyof PostsCommentsListResponses]

export type PostsCommentsCreateData = {
  body: CreateCommentRequest
  path: {
    postId: number
  }
  query?: never
  url: '/api/posts/{postId}/comments'
}

export type PostsCommentsCreateErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Not Found
   */
  404: unknown
}

export type PostsCommentsCreateResponses = {
  /**
   * Created
   */
  201: Comment
}

export type PostsCommentsCreateResponse =
  PostsCommentsCreateResponses[keyof PostsCommentsCreateResponses]

export type CommentsDeleteData = {
  body?: never
  path: {
    commentId: number
  }
  query?: never
  url: '/api/comments/{commentId}'
}

export type CommentsDeleteErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Not Found
   */
  404: unknown
}

export type CommentsDeleteResponses = {
  /**
   * No Content
   */
  204: void
}

export type CommentsDeleteResponse = CommentsDeleteResponses[keyof CommentsDeleteResponses]
