// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/vue-query'

import { client } from '../client.gen'
import {
  adminMdnPreload,
  commentsDelete,
  commentsRepliesCreate,
  commentsRepliesList,
  feedList,
  type Options,
  postsCommentsCreate,
  postsCommentsList,
  postsVotesToggle,
  resolveMdn,
  sessionMeGet,
  systemDbPing,
  systemHealth,
  topicsGetLinks,
  topicsGetPosts,
} from '../sdk.gen'
import type {
  AdminMdnPreloadData,
  AdminMdnPreloadResponse,
  CommentsDeleteData,
  CommentsDeleteResponse,
  CommentsRepliesCreateData,
  CommentsRepliesCreateResponse,
  CommentsRepliesListData,
  CommentsRepliesListResponse,
  FeedListData,
  FeedListResponse,
  PostsCommentsCreateData,
  PostsCommentsCreateResponse,
  PostsCommentsListData,
  PostsCommentsListResponse,
  PostsVotesToggleData,
  PostsVotesToggleResponse,
  ResolveMdnData,
  ResolveMdnResponse2,
  SessionMeGetData,
  SessionMeGetResponse,
  SystemDbPingData,
  SystemHealthData,
  TopicsGetLinksData,
  TopicsGetLinksResponse,
  TopicsGetPostsData,
  TopicsGetPostsResponse,
} from '../types.gen'

/**
 * Enqueues batch MDN fetch_raw jobs (dev/admin)
 */
export const adminMdnPreloadMutation = (
  options?: Partial<Options<AdminMdnPreloadData>>,
): UseMutationOptions<AdminMdnPreloadResponse, DefaultError, Options<AdminMdnPreloadData>> => {
  const mutationOptions: UseMutationOptions<
    AdminMdnPreloadResponse,
    DefaultError,
    Options<AdminMdnPreloadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminMdnPreload({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const topicsGetPostsQueryKey = (options: Options<TopicsGetPostsData>) =>
  createQueryKey('topicsGetPosts', options)

/**
 * Returns posts for a topic
 */
export const topicsGetPostsOptions = (options: Options<TopicsGetPostsData>) =>
  queryOptions<
    TopicsGetPostsResponse,
    DefaultError,
    TopicsGetPostsResponse,
    ReturnType<typeof topicsGetPostsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await topicsGetPosts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: topicsGetPostsQueryKey(options),
  })

export const topicsGetLinksQueryKey = (options: Options<TopicsGetLinksData>) =>
  createQueryKey('topicsGetLinks', options)

/**
 * Returns linked topics for a topic
 */
export const topicsGetLinksOptions = (options: Options<TopicsGetLinksData>) =>
  queryOptions<
    TopicsGetLinksResponse,
    DefaultError,
    TopicsGetLinksResponse,
    ReturnType<typeof topicsGetLinksQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await topicsGetLinks({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: topicsGetLinksQueryKey(options),
  })

export const systemHealthQueryKey = (options?: Options<SystemHealthData>) =>
  createQueryKey('systemHealth', options)

/**
 * Health check
 */
export const systemHealthOptions = (options?: Options<SystemHealthData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof systemHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await systemHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: systemHealthQueryKey(options),
  })

export const systemDbPingQueryKey = (options?: Options<SystemDbPingData>) =>
  createQueryKey('systemDbPing', options)

/**
 * Checks DB connectivity
 */
export const systemDbPingOptions = (options?: Options<SystemDbPingData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof systemDbPingQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await systemDbPing({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: systemDbPingQueryKey(options),
  })

export const sessionMeGetQueryKey = (options?: Options<SessionMeGetData>) =>
  createQueryKey('sessionMeGet', options)

/**
 * Returns the current user id from Supabase JWT
 */
export const sessionMeGetOptions = (options?: Options<SessionMeGetData>) =>
  queryOptions<
    SessionMeGetResponse,
    DefaultError,
    SessionMeGetResponse,
    ReturnType<typeof sessionMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await sessionMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: sessionMeGetQueryKey(options),
  })

export const resolveMdnQueryKey = (options: Options<ResolveMdnData>) =>
  createQueryKey('resolveMdn', options)

/**
 * Resolves an MDN external path to a DocTok topic
 */
export const resolveMdnOptions = (options: Options<ResolveMdnData>) =>
  queryOptions<
    ResolveMdnResponse2,
    DefaultError,
    ResolveMdnResponse2,
    ReturnType<typeof resolveMdnQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await resolveMdn({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: resolveMdnQueryKey(options),
  })

/**
 * Toggles a like or dislike on a post
 */
export const postsVotesToggleMutation = (
  options?: Partial<Options<PostsVotesToggleData>>,
): UseMutationOptions<PostsVotesToggleResponse, DefaultError, Options<PostsVotesToggleData>> => {
  const mutationOptions: UseMutationOptions<
    PostsVotesToggleResponse,
    DefaultError,
    Options<PostsVotesToggleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postsVotesToggle({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const feedListQueryKey = (options?: Options<FeedListData>) =>
  createQueryKey('feedList', options)

/**
 * Returns paginated feed items
 */
export const feedListOptions = (options?: Options<FeedListData>) =>
  queryOptions<
    FeedListResponse,
    DefaultError,
    FeedListResponse,
    ReturnType<typeof feedListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await feedList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: feedListQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const feedListInfiniteQueryKey = (
  options?: Options<FeedListData>,
): QueryKey<Options<FeedListData>> => createQueryKey('feedList', options, true)

/**
 * Returns paginated feed items
 */
export const feedListInfiniteOptions = (options?: Options<FeedListData>) =>
  infiniteQueryOptions<
    FeedListResponse,
    DefaultError,
    InfiniteData<FeedListResponse>,
    QueryKey<Options<FeedListData>>,
    string | Pick<QueryKey<Options<FeedListData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<FeedListData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await feedList({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: feedListInfiniteQueryKey(options),
    },
  )

export const commentsRepliesListQueryKey = (options: Options<CommentsRepliesListData>) =>
  createQueryKey('commentsRepliesList', options)

/**
 * Returns replies for a root comment
 */
export const commentsRepliesListOptions = (options: Options<CommentsRepliesListData>) =>
  queryOptions<
    CommentsRepliesListResponse,
    DefaultError,
    CommentsRepliesListResponse,
    ReturnType<typeof commentsRepliesListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await commentsRepliesList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: commentsRepliesListQueryKey(options),
  })

/**
 * Adds a reply to a root comment
 */
export const commentsRepliesCreateMutation = (
  options?: Partial<Options<CommentsRepliesCreateData>>,
): UseMutationOptions<
  CommentsRepliesCreateResponse,
  DefaultError,
  Options<CommentsRepliesCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    CommentsRepliesCreateResponse,
    DefaultError,
    Options<CommentsRepliesCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await commentsRepliesCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const postsCommentsListQueryKey = (options: Options<PostsCommentsListData>) =>
  createQueryKey('postsCommentsList', options)

/**
 * Returns root comments for a post
 */
export const postsCommentsListOptions = (options: Options<PostsCommentsListData>) =>
  queryOptions<
    PostsCommentsListResponse,
    DefaultError,
    PostsCommentsListResponse,
    ReturnType<typeof postsCommentsListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postsCommentsList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: postsCommentsListQueryKey(options),
  })

/**
 * Adds a comment to a post
 */
export const postsCommentsCreateMutation = (
  options?: Partial<Options<PostsCommentsCreateData>>,
): UseMutationOptions<
  PostsCommentsCreateResponse,
  DefaultError,
  Options<PostsCommentsCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostsCommentsCreateResponse,
    DefaultError,
    Options<PostsCommentsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postsCommentsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Soft-deletes a comment owned by the current user
 */
export const commentsDeleteMutation = (
  options?: Partial<Options<CommentsDeleteData>>,
): UseMutationOptions<CommentsDeleteResponse, DefaultError, Options<CommentsDeleteData>> => {
  const mutationOptions: UseMutationOptions<
    CommentsDeleteResponse,
    DefaultError,
    Options<CommentsDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await commentsDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
