alter table public.raw_documents
  add column if not exists sections_jsonb jsonb not null default '[]'::jsonb;

alter table public.posts
  add column if not exists source_section_key text not null default '',
  add column if not exists is_active boolean not null default true;

create unique index if not exists ux_posts_doc_lang_source_section_key
  on public.posts(raw_document_id, lang, source_section_key)
  where source_section_key <> '';

create table if not exists public.post_content_variants (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  variant_code text not null,
  title text,
  body text not null,
  body_html text not null default '',
  provider text,
  model text,
  prompt_version text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint post_content_variants_variant_code_check
    check (variant_code ~ '^[a-z0-9_]+$'),
  constraint post_content_variants_post_variant_key
    unique(post_id, variant_code)
);

create index if not exists ix_post_content_variants_post_variant
  on public.post_content_variants(post_id, variant_code);
